### ISSUE TITLE
Is this the Open-source version of CircleCI? 

### ISSUE THREAD

**Issue by marcellodesales** [circleci/frontend#18]
Question
--------
Can I run this in my private infrastructure before I engage in any POC?

Situation
-------
Is there a way to use this to introduce CircleCI to our Engineering teams before engaging in a more in-depth POC? That way, it would be easier to convince influential teams to start looking at CircleCI as an alternative to Jenkins...

What does this Frontend can give us?

thanks!

**Comment by Peeja** [comment]
This isn't CircleCI itself, this is just the frontend. It talks to CircleCI over an API. You could run a local fork of the frontend if you wanted to make it look different, but you'd still be talking to CircleCI and you'd still need a CircleCI account.

**Comment by worldsoup** [comment]
Hey Marcello,
Like Peeja mentioned, this is only the front end and can't actually be deployed to run a private CircleCI instance. The quickest/easiest way is to have team members run personal or open-source projects on circleci.com, otherwise I'm happy to get a test instance of CircleCI Enterprise setup for you to try on your own infrastructure.

**Comment by startling** [comment]
I'm going to close this for now. Let us know if there's anything else we can help with!
