### ISSUE TITLE
reify in let binding

### ISSUE THREAD

**Issue by fourq** [circleci/frontend#28]
According to David Nolen, there's a real issue with using reify within a let binding like the one used here: https://github.com/circleci/frontend/blob/master/src-cljs/frontend/components/contact_form.cljs#L70-L74 

He mentions it on his GH. "It's extremely important we don't do this in a let binding around reify. This is a common mistake."

Just a heads up.
<3

**Comment by fourq** [comment]
oh also, David mentioned that this kind of "accidental anti-pattern" is no longer be an issue in the next version (Om Next).

**Comment by Peeja** [comment]
@fourq Hey, great catch, thanks! You're referring to the [Basic Tutorial](https://github.com/omcljs/om/wiki/Basic-Tutorial#intercomponent-communication), correct? What he's saying there is not to do side-effect-y things in a `let` around `reify`, because it'll run every time the component's parent is rendered, rather than just when the component is mounted.

In *this* case, we're just giving a name to a function. It means we'll build a new copy of this function (`update-state`) every time `form-control` runs, which is fine. Since `update-state` depends on `owner` from the `form-control` arguments, we actually *need* to rebuild it each time `form-control` runs (since `owner` could in theory be different each time).

At least, I think that's right. If there's a flaw in that logic, please let me know!

**Comment by fourq** [comment]
hey @Peeja, just talked with dnolen about this and he mentioned that "if they thought it through that's ok, but I just recommend against it since it's hard to understand the semantics". Sorry for the issue, but thanks for the code =)

**Comment by Peeja** [comment]
Cheers! Did he mention any alternatives? In React, this would normally be an additional method on the component, and this seemed like the closest equivalent. Maybe there's no great answer until Om Next is out.

**Comment by fourq** [comment]
No, he didn't mention anything more about it, just what I quoted. Until Om Next.

Have a great one!
